// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMw-OjZcfE9xIvlMYeVKppTuLfH9kAaEg',
    appId: '1:326148138701:web:b4ce1e0136d36e881bab84',
    messagingSenderId: '326148138701',
    projectId: 'ta-project-mobileapps',
    authDomain: 'ta-project-mobileapps.firebaseapp.com',
    databaseURL: 'https://ta-project-mobileapps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ta-project-mobileapps.firebasestorage.app',
    measurementId: 'G-C80YDMGD6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRbgrbj0aWGSI9sy9OWKX3tsGdHBUdAxE',
    appId: '1:326148138701:android:46f65dfcd26b8e9c1bab84',
    messagingSenderId: '326148138701',
    projectId: 'ta-project-mobileapps',
    databaseURL: 'https://ta-project-mobileapps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ta-project-mobileapps.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYA7Y44VJ16M33xYW55PtSOd9O93FsE7Y',
    appId: '1:326148138701:ios:fa3ea725c4a732511bab84',
    messagingSenderId: '326148138701',
    projectId: 'ta-project-mobileapps',
    databaseURL: 'https://ta-project-mobileapps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ta-project-mobileapps.firebasestorage.app',
    iosBundleId: 'com.example.taProject',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYA7Y44VJ16M33xYW55PtSOd9O93FsE7Y',
    appId: '1:326148138701:ios:fa3ea725c4a732511bab84',
    messagingSenderId: '326148138701',
    projectId: 'ta-project-mobileapps',
    databaseURL: 'https://ta-project-mobileapps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ta-project-mobileapps.firebasestorage.app',
    iosBundleId: 'com.example.taProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMw-OjZcfE9xIvlMYeVKppTuLfH9kAaEg',
    appId: '1:326148138701:web:d44313fcdfa5d5751bab84',
    messagingSenderId: '326148138701',
    projectId: 'ta-project-mobileapps',
    authDomain: 'ta-project-mobileapps.firebaseapp.com',
    databaseURL: 'https://ta-project-mobileapps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ta-project-mobileapps.firebasestorage.app',
    measurementId: 'G-3YYMESEGZQ',
  );
}
